version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000" # internal only
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    entrypoint: >
      sh -c "certbot certonly --webroot -w /var/www/certbot
      --email oakarkyaw@gmail.com --agree-tos --no-eff-email
      -d supacartgym-backend.duckdns.org"

volumes:
  certbot-etc:
  certbot-var:

networks:
  app-network:
    driver: bridge
